### ISSUE TITLE
[feat] Add support for Eaton Z-Wave Outlet Model:  RFTR9605-TAW

### ISSUE THREAD

**Issue by JWise1203** [zwave-js/node-zwave-js#1766]
Please add support for this device. It currently shows up as Unknown for the Product and Code columns.

Also, Home Assistant control is buggy.

I have attached the JSON file

[node_5.txt](https://github.com/zwave-js/zwavejs2mqtt/files/5978053/node_5.txt)

**Comment by robertsLando** [comment]
I have moved the issue to the zwave-js repo

**Comment by AlCalzone** [comment]
@blhoward2 we don't have this device:
Product Manufacturer: 0x001a
Product Type: 0x5244
Product ID: 0x0000

**Comment by AlCalzone** [comment]
And @JWise1203 please further specify what you mean with
> Home Assistant control is buggy.

That is not a very specific problem description :)

**Comment by blhoward2** [comment]
This file did actually exist, they share a product type/id between two very similar outlets. 96505/96605

**Comment by JWise1203** [comment]
Thanks everyone, since the Product ID was different, will zwave-js be updated, or is there something I need to do on my end?

**Comment by blhoward2** [comment]
It'll be updated to list both but it's just a label. It makes no functional difference.
