### ISSUE TITLE
Namron Z-Wave Dimmer 400W (0xD005)

### ISSUE THREAD

**Issue by truffles003** [zwave-js/node-zwave-js#3236]
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

Namron Z-Wave Dimmer 400W

### Manufacturer ID

0x0438

### Product Type

0x0200

### Product ID

0xD005

### Is the device listed on the Z-Wave Alliance website?

https://products.z-wavealliance.org/products/3641

### Do you have a manual?

[Namron Zwave Dimmer 400W.pdf](https://github.com/zwave-js/node-zwave-js/files/7049495/Namron.Zwave.Dimmer.400W.pdf)
[dimmer-400w.txt](https://github.com/zwave-js/node-zwave-js/files/7049499/dimmer-400w.txt)

**Comment by truffles003** [comment]
Made the config file (.txt), havent figured out commiting yet :)
Based on: https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/devices/0x0438/dimmer2-400w.json

**Comment by AlCalzone** [comment]
https://docs.github.com/en/github/managing-files-in-a-repository/managing-files-on-github/adding-a-file-to-a-repository would be one way

**Comment by truffles003** [comment]
thanks, ill try that
