### ISSUE TITLE
Z-Wave Network slow / unable to heal nodes

### ISSUE THREAD

**Issue by oeiber** [zwave-js/node-zwave-js#3241]
Hi,
after restoring my crashed UZB1 Stick using ZMESerialUpdater my Z-Wave nodes responses sometames very slow (5 to 10 seconds). I tried to perform a network heal, but most of the nodes showing up with healing failed. Also healing a single node runs into the same failure.
I'm using following versions:
zwavejs2mqtt: 5.5.1
zwave-js: 8.2.1
 My UZB1 Stick runs firmware 5.39

Thank you for your help!

**Comment by robertsLando** [comment]
Please attach logs

**Comment by oeiber** [comment]
Here's the debug-log
[zwavejs2mqtt.log](https://github.com/zwave-js/zwavejs2mqtt/files/7056084/zwavejs2mqtt.log)

**Comment by robertsLando** [comment]
Please attach also zwave-js logs

**Comment by oeiber** [comment]
ok. where can i find them?

**Comment by AlCalzone** [comment]
See [driver log](https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report?id=driver-logs). Use loglevel `debug` or `silly` and **attach** it here as a file.

**Comment by oeiber** [comment]
[zwavejs2mqtt-store.zip](https://github.com/zwave-js/node-zwave-js/files/7062419/zwavejs2mqtt-store.zip)

**Comment by AlCalzone** [comment]
Okay, I do see a bunch of heals succeed but also a lot of them fail. Honestly, I don't know what can be done about that - the actual communication that fails is done by the controller outside of our control.

**Comment by oeiber** [comment]
Maybe it is related to the UZB1 firmware version?
Before restoring the stick, I also updated the firmware to the latest version.

**Comment by oeiber** [comment]
Update: In the meantime I tried to restore my backup to a different uzb1 stick, running the latest firmware: Same behavior. 
I‘m not sure if the problem is really related to the controller

**Comment by AlCalzone** [comment]
Might also be some of the nodes (the ones that fail to heal). If you can, try cutting their power for a few seconds. Also, if you haven't already, try putting your controller on a USB extension cord, away from metallic surfaces.

**Comment by oeiber** [comment]
using a usb cord and cyclong power did not help. can it probably be a problem with the lifeline associations?

**Comment by AlCalzone** [comment]
Nope, they have nothing to do with healing

**Comment by oeiber** [comment]
In the meantime I tried to restore, even older backups, to three different controllers. the behavior is still the same. Also endpoints, which are nearly positioned to the controller, are affected. Do you have an idea, which further teoubleshooting steps can be done?

**Comment by AlCalzone** [comment]
I guess moving the problematic nodes is out of the question?

**Comment by oeiber** [comment]
this would be rhe last option, because we are talking about 20 problematic nodes ;-)

**Comment by AlCalzone** [comment]
Could it be that they are all routing through 1 or 2 that are actually problematic?

**Comment by oeiber** [comment]
maybe. how can i see the routing topology?

**Comment by oeiber** [comment]
maybe. how can i see the routing topology?

**Comment by oeiber** [comment]
maybe. how can i see the routing topology?

**Comment by oeiber** [comment]
sorry, that was a really stupid question.
As I can see in the topology view a lot of them are speaking directly with the controller

**Comment by AlCalzone** [comment]
You won't know for sure though - that map just gives you an idea of possible routes. Which ones are actually used is a different story.
