### ISSUE TITLE
zen32 interviews fail

### ISSUE THREAD

**Issue by jjlawren** [zwave-js/node-zwave-js#3242]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within ZWaveJS2MQTT?

NO, my problem is NOT within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

Interviews of the zen32 scene controller begin but always fail to complete with a timeout at the same step of the process.

### Device information

Manufacturer: Zooz
Model name: zen32
Node ID in your network: 18

### How are you using `node-zwave-js`?

- [X] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [X] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version:
`node-zwave-js` branch: 8.2.1
`zwavejs2mqtt` branch: 5.5.1

### Did you change anything?

yes (please describe)

### If yes, what did you change?

Moved to a new 700-series controller, moved location of the controller. The distance from the controller is further, but not significantly.

### Did this work before?

Yes (please describe)

### If yes, where did it work?

Same device was previously paired (with some inclusion issues) back in https://github.com/zwave-js/node-zwave-js/issues/2183.

### Attach Driver Logfile

[zwavejs_2021-08-26.log](https://github.com/zwave-js/node-zwave-js/files/7061529/zwavejs_2021-08-26.log)

**Comment by AlCalzone** [comment]
> moved location of the controller

Try healing the network. That may have messed up the routing. Node 18 is communicating somewhat reliably, but there are repeated and lost messages involved, which is why the interview doesn't complete.

**Comment by jjlawren** [comment]
I mean that the location of the _new_ controller is in a different location. All devices were re-included on the new stick, and that new stick lives in a different part of my house. This is the only device that is giving problems.

I've healed the network for good measure and factory reset the zen32 multiple times. Inclusion always seems to fail at roughly the same point in the process.

**Comment by jjlawren** [comment]
Update: I've moved the new stick back to the location of the old stick it paired without issue. Must have been RF issues caused by the new location. Sorry for the invalid case.
