### ISSUE TITLE
Fibaro Roller Shutter 3 requires many tries to be added successfully using S2

### ISSUE THREAD

**Issue by JakubMacoun** [zwave-js/node-zwave-js#3479]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

YES, BUT a Home Assistant developer has told me to come here

### Is your problem within ZWaveJS2MQTT?

NO, my problem is NOT within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

**What causes the bug?**
Adding a device to the network using S2.

**What do you observe?**
It takes more tries to add the device successfully and securely. Sometimes, adding the device just fails and I end up with an empty device (called Node XX) with no functionality or sensors, sometimes, I have fully added device but after the device is added, a warning message about insecurely added device is shown (and the device info says it's insecure).

**What did you expect to happen?**
To add the device successfully and securely on the first try.

**Steps to reproduce the behavior:**
  1. Go to Settings -> Integrations -> Z-Wave JS -> Configure -> Add Node -> use default options (add securely if possible)
  2. Add device to the add mode (triple press S1 button)
  3. Wait
  4. Input PIN code
  5. Wait
  6. See adding dialog stuck and end up with an empty device OR see the success dialog with the warning message (added insecurely)

### Device information

Manufacturer: Fibaro
Model name: Roller Shutter 3 (FGR-223)
Node ID in your network: successfully added: 33, 36, 40 (I have 3 devices); unsucessfully added: numbers between

Z-Wave stick: Aeotec Gen5+ in RPi4

### How are you using `node-zwave-js`?

- [ ] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [X] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version: 2010.10.0 (Z-Wave JS addon: 0.1.45)

### Did you change anything?

yes (please describe)

### If yes, what did you change?

Updated HA to 2010.10.0 and re-added devices using S2 (see description above)

### Did this work before?

Yes (please describe)

### If yes, where did it work?

It did work using no security on both old version and the new one.

### Attach Driver Logfile

Device adding fails: [zwave_js_not_working.log](https://github.com/zwave-js/node-zwave-js/files/7310654/zwave_js_not_working.log)
Device not added securely: [zwave_js_insecure.log](https://github.com/zwave-js/node-zwave-js/files/7310655/zwave_js_insecure.log)

Final successful adding: [zwave_js_success_after_double_fail_and_insecure.log](https://github.com/zwave-js/node-zwave-js/files/7310687/zwave_js_success_after_double_fail_and_insecure.log)

**Comment by AlCalzone** [comment]
This is from the one labeled "device adding fails", so the inclusion itself works:
```
2021-10-08T09:19:15.310Z CNTRLR   [Node 037] Security S2 bootstrapping successful with these security classes:
                                  · S2_Authenticated
                                  · S2_Unauthenticated
                                  · S0_Legacy
```

The problem happens during the interview where the controller and node get out of sync when querying the CC versions. I'll need your network key for S2_Authenticated to figure out what exactly - please send it to the email address in my profile, referencing this issue.

**Comment by JakubMacoun** [comment]
I sent my S2_Authenticated key to your email address, @AlCalzone

**Comment by AlCalzone** [comment]
I just remembered - I have nothing in place to follow the multi-stage decryption from logfiles, so that doesn't help terribly well.

There is something in your logs however, which hints at the underlying problem.
Some nodes involved in routing seem to unnecessarily re-transmit messages. You can see it in the inclusion logs where logs like this show up a couple of times:
```
2021-10-08T08:59:39.997Z DRIVER   Dropping message with invalid payload
2021-10-08T08:59:39.999Z DRIVER « [Node 035] [REQ] [ApplicationCommand]
                                  └─[Security2CCNonceGet] [INVALID]
                                      error: Duplicate command
...
2021-10-08T08:59:40.868Z DRIVER « [Node 035] [REQ] [ApplicationCommand]
                                  └─[Security2CCNonceReport] [INVALID]
                                      error: Duplicate command
...
2021-10-08T08:59:40.911Z DRIVER « [Node 035] [REQ] [ApplicationCommand]
                                  └─[Security2CCMessageEncapsulation] [INVALID]
                                      error: Duplicate command
```

And one big example at the start of the last logfile:
```
2021-10-08T09:29:03.470Z DRIVER « [Node 015] [REQ] [ApplicationCommand]
                                  └─[NotificationCCReport]
                                      notification type:   7
                                      notification status: 255
                                      notification state:  idle
                                      event parameters:    0x08
...
2021-10-08T09:29:03.487Z DRIVER « [Node 015] [REQ] [ApplicationCommand]
                                  └─[NotificationCCReport]
                                      notification type:   7
                                      notification status: 255
                                      notification state:  idle
                                      event parameters:    0x08
...
2021-10-08T09:29:03.667Z DRIVER « [Node 015] [REQ] [ApplicationCommand]
                                  └─[NotificationCCReport]
                                      notification type:   7
                                      notification status: 255
                                      notification state:  idle
                                      event parameters:    0x08
...
2021-10-08T09:29:03.824Z DRIVER « [Node 015] [REQ] [ApplicationCommand]
                                  └─[NotificationCCReport]
                                      notification type:   7
                                      notification status: 255
                                      notification state:  idle
                                      event parameters:    0x08

...

2021-10-08T09:29:06.962Z DRIVER « [Node 015] [REQ] [ApplicationCommand]
                                  └─[NotificationCCReport]
                                      notification type:   Home Security
                                      notification status: 255
                                      notification state:  Motion detection
...
2021-10-08T09:29:07.273Z DRIVER « [Node 015] [REQ] [ApplicationCommand]
                                  └─[NotificationCCReport]
                                      notification type:   Home Security
                                      notification status: 255
                                      notification state:  Motion detection
...
2021-10-08T09:29:07.537Z DRIVER « [Node 015] [REQ] [ApplicationCommand]
                                  └─[NotificationCCReport]
                                      notification type:   Home Security
                                      notification status: 255
                                      notification state:  Motion detection
```

I'm pretty sure that the latter are just 1 command each (notice the timestamps), unnecessarily re-transmitted 2-3 times somewhere along the route. This puts unnecessary load on the network and can trip up communication where the sequence is important (like during secure inclusion).

This problem usually hints at messed up routes or nodes with interference problems. You can try healing the network to reduce these. If that doesn't help, you'll have to dig deeper with the help of a Zniffer.

**Comment by JakubMacoun** [comment]
Network was healed some time before I started re-adding the nodes. It is however possible that there is some interference, as the devices are inside the wall switches.
Currently, all the nodes are added, so my network has no problems now. Unfortunatelly, I can't reproduce since I have no out-of-wall device that supports S2.
