### ISSUE TITLE
`yarn lint:config` fails in gitpod workspace

### ISSUE THREAD

**Issue by kpine** [zwave-js/node-zwave-js#3531]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within ZWaveJS2MQTT?

NO, my problem is NOT within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug?

Not sure, it seems like the workspace is not setup completely.

What do you observe?

An error trying to run `yarn lint:config`

```text
gitpod /workspace/node-zwave-js $ yarn lint:config
/workspace/node-zwave-js/.pnp.cjs:26483
    throw firstError;
    ^

Error: Required package missing from disk. If you keep your packages inside your repository then restarting the Node process may be enough. Otherwise, try to run an install first.

Missing package: lerna@npm:4.0.0
Expected package location: /home/gitpod/.yarn/berry/cache/lerna-npm-4.0.0-1d3a89023c-8.zip/node_modules/lerna/

    at Function.external_module_.Module._resolveFilename (/workspace/node-zwave-js/.pnp.cjs:26482:55)
    at Function.external_module_.Module._load (/workspace/node-zwave-js/.pnp.cjs:26281:48)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47
```

What did you expect to happen?

The command to not fail. If I run `yarn` then it looks like it installs necessary dependencies and then the command will work. My understanding though was that this workspace sets up everything to begin with to make it as easy as possible to contribute. If the initial `yarn` command is required, maybe the help text when starting should explain it?

  1. Open the workspace in a brand new gitpod workspace
  2. After answer the fork question, and the setup completes, run `yarn lint:config`.
  3. See error

### Device information

N/A

### How are you using `node-zwave-js`?

- [ ] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [ ] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [X] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

Default branch in workspace.

### Did you change anything?

no

### Did this work before?

No, it never worked anywhere

### Attach Driver Logfile

N/A

**Comment by AlCalzone** [comment]
Mhh looks like yarn is looking for the cache in the wrong directory. It should be in `/workspace/node-zwave-js/.yarn/cache` I think.
