### ISSUE TITLE
Missing device configuration: Fortrezz Siren SSA3

### ISSUE THREAD

**Issue by zanna1972** [zwave-js/node-zwave-js#3534]
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

Fortrezz SSA 3 Siren

### Manufacturer ID

0x0084

### Product Type

0x0331

### Product ID

0x010b

### Firmware Version

1.11

### Do you have a manual?

Hi, this is the manual.
[Sirena ssa-03_p4_user_manual_9sep2013.pdf](https://github.com/zwave-js/node-zwave-js/files/7359532/Sirena.ssa-03_p4_user_manual_9sep2013.pdf)

This is the part of the z-wave JS network, exported from Home Assistant concerning the SSA3 device.
![Downloaded JSON network - node 61](https://user-images.githubusercontent.com/92396381/137621698-82529f2f-f17a-413d-b8c8-7ed55e896d21.png)

I searched in the Z-Wave JS database and Fortrezz - SSA3 already exists. The manufacturer id is the same I see in the network file exported from Z-wave JS integration, but the type and product are different and not included in the database.
I hope I gice you all the information you need.
Many thanks in advance.

**Comment by AlCalzone** [comment]
@zwave-js-bot add fingerprint 0x0331:0x010b to 0x0084:0x0341:0x0205

**Comment by zanna1972** [comment]
Hi, thank you for your job. Sorry but I'm new in GitHub and in Z-Wave JS, so I don't knwo what a PR #3537 is and what I have to do. Please, could you explain me? Many thanks again. Appreciated.

**Comment by AlCalzone** [comment]
Nothing, just wait for the next release :)
