### ISSUE TITLE
Aeotec Nano Switch is now unknown product with 8.5.0

### ISSUE THREAD

**Issue by matejdro** [zwave-js/node-zwave-js#3542]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within ZWaveJS2MQTT?

NO, my problem is NOT within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### What causes the bug?

Update from 8.4.1 to 8.5.0

### What do you observe?

All nano switches are labelled as unknown product:

![image](https://user-images.githubusercontent.com/507922/137640782-79a771d4-1bc5-4e83-9c52-fe598da26e27.png)

### What did you expect to happen?

Switches to work properly like they did in 8.4.1

### Device information

[node_52.json.txt](https://github.com/zwave-js/node-zwave-js/files/7360636/node_52.json.txt)

https://devices.zwave-js.io/?jumpTo=0x0086:0x0003:0x0074:3.0

https://github.com/zwave-js/node-zwave-js/blob/b70d32963bb3c40d7586b49a46ed1f123c8c0940/packages/config/config/devices/0x0086/zw116.json#L12

### How are you using `node-zwave-js`?

- [X] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [ ] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version:
`node-zwave-js` branch: 8.5.0
`zwavejs2mqtt` branch: 5.9.0

### Did you change anything?

no

### Attach Driver Logfile

[interview_log.log](https://github.com/zwave-js/node-zwave-js/files/7360634/interview_log.log)

**Comment by AlCalzone** [comment]
That's not a [driver log](https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/generating-logs?id=driver-logs)

**Comment by matejdro** [comment]
Sorry, here is the proper log:
[zwavejs_interview.log](https://github.com/zwave-js/node-zwave-js/files/7361858/zwavejs_interview.log)

**Comment by AlCalzone** [comment]
I can see it in the log, but I cannot reproduce. Can you try locating the file `0x0086/zw116.json` in your container and/or in the `storage/.config-db` folder and post it?

**Comment by matejdro** [comment]
I just found out that I had old config file there that I played around long time ago and forgot about it. Looks like it is not compatible anymore. Deleted my custom config and now everything works fine.

Thanks a lot for your help and sorry for bugging you for this.
