### ISSUE TITLE
DRIVER the node is unknown or not initialized yet, discarding...

### ISSUE THREAD

**Issue by HubertusH** [zwave-js/node-zwave-js#3552]
### Version

**Checklist:**

- [X] I am **not** using Home Assistant. **Or:** a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is **not** described there.
- [X] I have read the changelog and my problem is **not** mentioned there.

Build/Run method

- [ ] Docker
- [ ] PKG
- [X] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

Zwavejs2Mqtt version: 5.8.0.36f1b6b
Z-Wave JS version: 8.4.1

### Describe the bug

in my log appears a device-id 74 which does not exist anymore. The controller and also the dashboard does not know this device-id. The device used to exist - but was removed.

### To Reproduce

see the log ...

      2021-10-19T14:17:13.037Z DRIVER the node is unknown or not initialized yet, discarding...
      2021-10-19T14:17:13.112Z SERIAL « 0x01130004004a0d600d02ff7105000000ff070800bb (21 bytes)
      2021-10-19T14:17:13.114Z SERIAL » [ACK] (0x06)
      2021-10-19T14:17:13.115Z DRIVER « [Node 074] [REQ] [ApplicationCommand]
      └─[MultiChannelCCCommandEncapsulation]
      │ source: 2
      │ destination: 1, 2, 3, 4, 5, 6, 7
      └─[NotificationCCReport]
      notification type: Home Security
      notification status: 255
      notification state: Motion detection
      2021-10-19T14:17:13.117Z DRIVER the node is unknown or not initialized yet, discarding...
      2021-10-19T14:17:13.197Z SERIAL « 0x01130004004a0d600d02ff7105000000ff070800bb (21 bytes)
      2021-10-19T14:17:13.198Z SERIAL » [ACK] (0x06)
      2021-10-19T14:17:13.200Z DRIVER « [Node 074] [REQ] [ApplicationCommand]
      └─[MultiChannelCCCommandEncapsulation]
      │ source: 2
      │ destination: 1, 2, 3, 4, 5, 6, 7
      └─[NotificationCCReport]
      
### Additional context

Thank you

**Comment by AlCalzone** [comment]
I need to see a driver log of the first couple of seconds of the startup. Please attach it as a file.

**Comment by HubertusH** [comment]
Here it come - i hope this is the right one.

[zwavejs2mqtt_2021-10-20.zip](https://github.com/zwave-js/node-zwave-js/files/7380724/zwavejs2mqtt_2021-10-20.zip)

**Comment by HubertusH** [comment]
mysterious - the node 74 was, however, removed from the controller and was no longer visible in the dashboard. Since the associated lamp is not directly accessible, I had "forgotten" about it. It looks like the lamp wants to make contact with the controller, which no longer knows it. I have removed the lamp from the power and now the error message no longer appears in the log.

The question remains why the node disappears from the controller? Have the case now for the second time. Is there an internal routine that, for whatever reason, triggers a remove?

Thanks so far
Hubertus

**Comment by AlCalzone** [comment]
That's not a [driver log](https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/generating-logs?id=driver-logs).

A node isn't automatically removed, unless a reset notification was received from it. But that only happens if the node is factory-reset and supports the CC.

Other reasons could be:
- The node was sleeping or unreachable and you used the Remove Failed Node or Replace Failed Node function.
- The stick's memory got corrupted

**Comment by AlCalzone** [comment]
Did you find out what it was?
