### ISSUE TITLE
[Bug]: Fibaro nodes do not sent button events

### ISSUE THREAD

**Issue by dionmes** [zwave-js/node-zwave-js#3569]
### What happened?

I cannot recall which version update this caused. But the controller node as the devices nodes do no report physical button presses anymore. So this means when I use my physical switch (for example the kitchen) it does not report this to nodered.

So the situation was, the UI dashboard (and homekit) got synchronised when using the physical button because it would trigger a value change. This is not happening anymore, cause no value change event is sent. I really cannot recall when this issue was introduced.

### How to reproduce?

Use the physical switch and see that it does not create a value change event.

### Version

6.1.1 and 6.2.0

### Node-RED Version

2.0.6

### What hardware are you seeing the problem on?

Raspberry Pi

### Relevant Z-Wave-JS log output

```shell
None thats the problem :)
```

**Comment by marcus-j-davies** [comment]
Hi @dionmes,

We really need a log, of when you push the button - if you are saying that nothing is happening in the log when you push the button, then the switch is not sending anything - the log will log EVERY communication being sent to the controller whether it is seen in node red or not.

Please set log to `debug` do a physical button click, and attach the log as a file here.
without a log - we cant really begin to investigate - disable logging after (it fills up quickly)

you can of course attempt a single node heal, or check over the associations - I cant think of anything that will change associations  - but its worth a check never the less.

Edit:
only 1 update has occurred 6.1.1 -> 6.2.0 (so you haven't jumped much)

**Comment by marcus-j-davies** [comment]
Hi @dionmes,

Please can you attach the file as is.

**Comment by dionmes** [comment]
With initialization and a manual switch action at the end (node 13).
[zwave-js-log.txt](https://github.com/zwave-js/node-red-contrib-zwave-js/files/7371478/zwave-js-log.txt)

**Comment by dionmes** [comment]
That would be this ?
<img width="771" alt="IMG_0018" src="https://user-images.githubusercontent.com/8571217/137919051-9b583074-60fa-46dc-8253-e91f4d63716b.png">

**Comment by marcus-j-davies** [comment]
OK that's fine - thanks for now.

**Comment by AlCalzone** [comment]
This is likely due to some of the changes related to the endpoint/association mess, although there were only bugfixes in 8.5.0 but who knows... Did you try a re-interview yet?

**Comment by dionmes** [comment]
Yes this still occurs. Only not always, this is when I switched it off/on with the physical switch:

```
2021-10-19T16:48:51.879Z SERIAL « 0x01090004000d03250300da                                            (11 bytes)
2021-10-19T16:48:51.883Z CNTRLR   [Node 013] [~] [Binary Switch] currentValue: true => false        [Endpoint 0]
2021-10-19T16:48:51.886Z CNTRLR   [Node 013] [+] [Binary Switch] targetValue: undefined             [Endpoint 0]
2021-10-19T16:48:51.887Z NDERED » [Node: 13] [VALUE_UPDATED] [DIRECT] Forwarding payload...
2021-10-19T16:48:51.888Z NDERED » [Node: 13] [VALUE_UPDATED] [EVENT] Forwarding payload...
2021-10-19T16:48:51.889Z SERIAL » [ACK]                                                                   (0x06)
2021-10-19T16:48:51.894Z DRIVER « [Node 013] [REQ] [ApplicationCommand]
                                  └─[BinarySwitchCCReport]
                                      current value: false
2021-10-19T16:48:59.836Z SERIAL « 0x01090004000d032503ff25                                            (11 bytes)
2021-10-19T16:48:59.839Z CNTRLR   [Node 013] [~] [Binary Switch] currentValue: false => true        [Endpoint 0]
2021-10-19T16:48:59.840Z SERIAL » [ACK]                                                                   (0x06)
2021-10-19T16:48:59.842Z DRIVER « [Node 013] [REQ] [ApplicationCommand]
                                  └─[BinarySwitchCCReport]
                                      current value: true
```

**Comment by dionmes** [comment]
[zwave-js-log.txt](https://github.com/zwave-js/node-red-contrib-zwave-js/files/7375614/zwave-js-log.txt)

Or do you want a new one ?

**Comment by marcus-j-davies** [comment]
A new one since the re-interview might see differences.

remember to upload as is - try not to make any changes to the log 👍

**Comment by dionmes** [comment]
So can I ask what you are looking for ? I have done some work on the openzwave node-red module, very limited but have been playing around with zwave for a while now.
[https://flows.nodered.org/node/node-red-contrib-openzwave
](url)

**Comment by marcus-j-davies** [comment]
At the moment, it's unclear why certain `value updated` events are not triggering, especially when they are different values each time.

even more odd - its only the Fibaro devices you have reported, but the driver is indeed receiving them.

I don't have fibaro devices - but yet, every value update is triggered from the driver on my end, I Don't have any other reports of this kind (I don't know if they use Fibaro)

@AlCalzone is all over logs, so this **_might_** reveal something, that I cant see.
This NR module subscribes to `value updated` events from the driver - but it would seem they are not being triggered, both as per your report, and the logs are not spitting out entries that suggests it has received the event from zwave-js.

Edit:
Of course this might be something inside NR - but I can't see it currently.

**Comment by dionmes** [comment]
Ok, so if I understand correctly, the node.on method in node-red-contrib-zwave-js is not receiving the value updates. zwave-js is showing them in the log messages but it is not creating the events ?

**Comment by marcus-j-davies** [comment]
That would be my current understanding.
Other devices are triggering - so there is no pattern to it.

I get all events - but then I don't use fibaro

**Comment by AlCalzone** [comment]
@dionmes The logs you posted don't include a re-interview of the node.

To clarify, what could be happening is that the devices are reporting from endpoint 0, but zwave-js hides this one in favor of endpoints >=1 to prevent duplicates. A re-interview should show how the lifeline associations are set up and potentially re-configure them if they were incorrect (e.g. to report from the other endpoints).

**Comment by dionmes** [comment]
I am a bit reluctant to share the complete 4.3mb log file I have right now. There can be too much info extracted from that.
Anyway this was the interview of node 13
[zwave-js-interview.log](https://github.com/zwave-js/node-red-contrib-zwave-js/files/7379005/zwave-js-interview.log)
;

**Comment by marcus-j-davies** [comment]
Thanks @dionmes.

@AlCalzone, is there anything from my end you need?
If it's found to be driver side, transfer if it's easier, if not, let me know and I'll dig deeper this end.

**Comment by AlCalzone** [comment]
Ok this log has highlighted a little bug in the association setup, but that shouldn't be the issue here since the association is already set up correctly. I think this has to do with the useless endpoints on this device. Let's transfer this to the driver repo and investigate there.

**Comment by AlCalzone** [comment]
Alternative attempt:
@zwave-js-bot add compat flag to `0x010f:0x0402:0x1002:2.2`
```jsonc
// The device sends reports from endpoint 1 un-encapsulated
mapRootReportsToEndpoint: 1
```

**Comment by AlCalzone** [comment]
@zwave-js-bot add compat flag to 0x010f:0x0402:0x1002:2.2
```jsonc
// The device has two switch endpoints but they are not needed
preserveRootApplicationCCValueIDs: true,
preserveEndpoints: []
```

**Comment by AlCalzone** [comment]
Alternative attempt:
@zwave-js-bot add compat flag to 0x010f:0x0402:0x1002:2.2
```jsonc
// The device sends reports from endpoint 1 un-encapsulated
mapRootReportsToEndpoint: 1
```

**Comment by AlCalzone** [comment]
@dionmes We need to test which approach is better here.
File 1: https://raw.githubusercontent.com/zwave-js/node-zwave-js/2f9af2d27449a821cb0ee92aa73b446563c216b3/packages/config/config/devices/0x010f/fgs212.json
File 2: https://raw.githubusercontent.com/zwave-js/node-zwave-js/41bb6ea1df02b6b2be614f202e4a5ed9917122a7/packages/config/config/devices/0x010f/fgs212.json

The node red plugin allows you to specify a directory for custom config files (Custom CFG Dir). Please put file 1 there, re-interview the node and check if your issue is resolved (best make a log of the switching attempts and post it).
If not, put file 2 there and do the same.

**Comment by marcus-j-davies** [comment]
@dionmes,

Don't set this to a root dir - as it will be scanned recursively for config files.
best create a directory say  `/home/user/ZwaveCustomConfigs` or something to that affect, use this location in the node config, place the test configs in there, restart the controller (renaming should be good enough), then reinterview.

Whenever trying new config files in this directory, a restart of the controller is needed + the re-interview.

**Comment by dionmes** [comment]
Thx, I will try out this evening, daily meetings get in the way :)

**Comment by dionmes** [comment]
So here they are, for both device config files.
[zwave-js1.log](https://github.com/zwave-js/node-zwave-js/files/7391504/zwave-js1.log)
[zwave-js2.log](https://github.com/zwave-js/node-zwave-js/files/7391505/zwave-js2.log)

Nothing changed. But to be honest I think the config files direction is not the right direction. These switches are ancient (couple of years) and probably also the config files. The issue started after an update of node-red-contrib-zwave-js. And I really doubt the device config file was changed.

**Comment by marcus-j-davies** [comment]
Ok,

The files did not take - so it's still using the old config files, so the changes to the configs, could still be a fix here.
Log shows that it could not find a referenced template file, in our test config

```
2021-10-21T16:33:42.217Z CONFIG   Error parsing config file fgs212.json: Could not parse config file /home/pi/zw
                                  ave_tst_cfg/templates/master_template.json: ENOENT: no such file or directory,
                                   open '/home/pi/zwave_tst_cfg/templates/master_template.json'
                                  Import stack: 
                                    in #state_after_power_failure_off_prev
                                    in /home/pi/zwave_tst_cfg/fgs212.json
```

Please copy the contents of:
`/home/pi/.node-red/node_modules/@zwave-js/config/config/devices/templates/`

And paste here
`/home/pi/zwave_tst_cfg/templates/`

@AlCalzone  - unless there is a quicker way?

**Comment by dionmes** [comment]
I have copied both versions (not at the same time) to their original location in the config dir. associated with the zwave-js module. Rebooted for both, interviewed for both. No go. I am sorry but this is not the right direction.

**Comment by marcus-j-davies** [comment]
Ok,

The event mechanism is a simple subscription to `value updated` + others - which is the same for all nodes.
and you're getting them, apart from these Fibaro devices.

I'll wait for AI, as I am at a loss at this stage.

> The issue started after an update of node-red-contrib-zwave-js

The only note worthy change here was a bump to zwave-js 8.5.0

**Comment by dionmes** [comment]
I understand, but the events are viewable in the log. So the driver is receiving them.

**Comment by dionmes** [comment]
So again looking at the logs, the difference are these;
```
2021-10-21T17:36:39.029Z NDERED » [Node: 13] [VALUE_UPDATED] [DIRECT] Forwarding payload...
2021-10-21T17:36:39.030Z NDERED » [Node: 13] [VALUE_UPDATED] [EVENT] Forwarding payload...
2021-10-21T17:36:39.031Z NDERED » [Node: 13] [VALUE_UPDATED] [DIRECT] Forwarding payload...
2021-10-21T17:36:39.032Z NDERED » [Node: 13] [VALUE_UPDATED] [EVENT] Forwarding payload...
```
So where in the zwave-js driver does that happen, I would love to know.

**Comment by marcus-j-davies** [comment]
Yeah, I saw that, I should really destroy any listeners before subscribing or call `once` instead of `on` for `ready`
The event `ready` is used to then subscribe to the various updates on the associated node.

but `ready` is triggered after an interview also, so doing another interview, stacks another subscription  on the value events - hence the duplicated log entries (and events into NR)

It doesn't explain that some of them are not triggering, or appear to receive a `value updated` event
```
021-10-21T16:35:03.414Z CNTRLR   [Node 013] [~] [Binary Switch] currentValue: true => false        [Endpoint 0]
2021-10-21T16:35:03.416Z SERIAL » [ACK]                                                                   (0x06)
2021-10-21T16:35:03.420Z DRIVER « [Node 013] [REQ] [ApplicationCommand]
                                  └─[BinarySwitchCCReport]
                                      current value: false
2021-10-21T16:35:09.300Z SERIAL « 0x01090004000d032503ff25                                            (11 bytes)
2021-10-21T16:35:09.304Z CNTRLR   [Node 013] [~] [Binary Switch] currentValue: false => true        [Endpoint 0]
2021-10-21T16:35:09.305Z SERIAL » [ACK]                                                                   (0x06)
2021-10-21T16:35:09.308Z DRIVER « [Node 013] [REQ] [ApplicationCommand]
                                  └─[BinarySwitchCCReport]
                                      current value: true
```

**Comment by dionmes** [comment]
My best guess at the moment is that its in the Endpoint.ts part of zwave.js. That is the most relevant code with the most recent changes, but hey what do I know.

**Comment by marcus-j-davies** [comment]
I am still not ruling out the NR side - but all other devices seem fine i.e your meter updates, multilevel sensor updates etc etc don't skip a beat, but the Fibaro' seem sporadic - although they are received by the driver.

**Comment by dionmes** [comment]
That is not a good comparison. Those are sensors, so no local action is being done, just status updates. And when I do a value update of the fibaro devices than I also get the right response. Although a fibaro dimmer does respond correctly on local updates, but thats a more recent device.

**Comment by marcus-j-davies** [comment]
Oh for Sure,

it was more to confirm that the way we are listening for value updates, isn't playing up, hence NR should be receving them for your Fibaro'

Unless something is found in the driver - I still have NR under the microscope.

**Comment by AlCalzone** [comment]
This is definitely happening in the driver and needs to be handled with a config change. This is a single-channel device but for some weird reason uses two (!) identical switch endpoints to expose its functionality but then does not report via the endpoint(s), which makes no sense at all.

> open '/home/pi/zwave_tst_cfg/templates/master_template.json'

Damn... I looked for the imports but didn't spot them.
Ok, so put [this file](https://raw.githubusercontent.com/zwave-js/node-zwave-js/master/packages/config/config/devices/templates/master_template.json) in the subdirectory `templates` in your test dir

Then do as I described in https://github.com/zwave-js/node-zwave-js/issues/3569#issuecomment-948461773 - make sure to put the files in the root of the test directory.

> But to be honest I think the config files direction is not the right direction

Just trust the guy who has worked thousands of hours of his life on this, will you? 😉

**Comment by dionmes** [comment]
Ok, tried it with the template file and the first fgs212 file solves the issue. I now get the responses using the physical switch attached to the node. Good one.

**Comment by marcus-j-davies** [comment]
Nice!
Entering into NR with no issues?

Not sure if @AlCalzone has any other plans with this one, but the config file changes, will make it Into release, if there are no further issues with this config file.

Edit:
Once its in release (and you update the config DB or the driver version) - you can remove the config file(s) from your test dir, restart, re-interview.

**Comment by dionmes** [comment]
Yes, did some testing all seem to reporting ok. Will keep the config in the test dir until an update. Thx all.

**Comment by AlCalzone** [comment]
Thanks for testing!
