### ISSUE TITLE
Inovelli LZW36 - Fan turning off after 2h10m (just like #2159)

### ISSUE THREAD

**Issue by itpeters** [zwave-js/node-zwave-js#3594]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within ZWaveJS2MQTT?

NO, my problem is NOT within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug?

I have an Inovelli LZW36 Red Series Fan + Light Switch that was previously working correctly with Hubitat. I excluded the device and included it via the Z-Wave JS addon in HA. I have also since tried excluding the device, resetting it, and then reincluding it.

What do you observe?

The fan turns off by itself after 2 hours and 10 minutes.

What did you expect to happen?

The fan to remain on after being turned on until turned off.

  1. Turn on the fan via HA.
  2. Wait for 2 hours and 10 minutes.
  3. The fan turns off.

### Device information

Manufacturer: Inovelli
Model name: LZW36
Node ID in your network: 41

### How are you using `node-zwave-js`?

- [ ] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [X] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

Home Assistant Z-Wave JS addon version: 0.1.45
Z-Wave JS Server: 1.10.7
Z-Wave JS: 8.4.1

### Did you change anything?

no

### Did this work before?

Don't know, this is a new device

### Attach Driver Logfile

[zwave_js.log](https://github.com/zwave-js/node-zwave-js/files/7414087/zwave_js.log)

**Comment by itpeters** [comment]
The LZW36 firmware is version 1.34.

The attached log captures turning the fan on. This section:

```
2021-10-25T23:45:48.331Z DRIVER » [Node 041] [REQ] [SendDataBridge]
                                  │ source node id:   1
                                  │ transmit options: 0x25
                                  │ route:            0, 0, 0, 0
                                  │ callback id:      238
                                  └─[Security2CCMessageEncapsulation]
                                    │ sequence number: 73
                                    └─[MultiChannelCCCommandEncapsulation]
                                      │ source:      0
                                      │ destination: 2
                                      └─[SupervisionCCGet]
                                        │ session id:      27
                                        │ request updates: true
                                        └─[MultilevelSwitchCCSet]
                                            target value: 255
```

looks the same as the problematic component of #2159. Combined with the matching time frame, I suspect it's the same issue.

I did see in https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md the following fix from 8.6.0:

> Avoid force-adding Supervision support, remove encapsulation CCs from list of mandatory CCs

If this is potentially related or the cause of the regression, I can turn my attention to getting the HA addon updated.

**Comment by kpine** [comment]
You can also re-include the device without security, if you need a quick fix.

**Comment by AlCalzone** [comment]
8.5.1/8.6.0 should fix this.

**Comment by AlCalzone** [comment]
If not, please reopen with fresh logs after re-interviewing the device on the latest version.

**Comment by itpeters** [comment]
Thanks @AlCalzone + @kpine. After updating today and re-interviewing the device, everything is working perfectly again.
