### ISSUE TITLE
Error: api remove association - All node IDs must be between 1 and 232

### ISSUE THREAD

**Issue by HubertusH** [zwave-js/node-zwave-js#3606]
### Discussed in https://github.com/zwave-js/node-zwave-js/discussions/3605

<div type='discussions-op-text'>

<sup>Originally posted by **HubertusH** October 27, 2021</sup>
i have a node with associations to node 243 and 255
![image](https://user-images.githubusercontent.com/16612146/139119237-861daace-f7f2-4733-8dcd-54ab6c2f5218.png)
if i delete them with the api call removeAssociation i get the error:
`2021-10-27 19:33:23.860 WARN ZWAVE: Error while removing associations from Node 25: All node IDs must be between 1 and 232! (ZW0322)
`
now the question is - how to remove this associations?

Thank you for your support
br
Hubertus</div>

**Comment by AlCalzone** [comment]
This check is a bit strict for the removal part, I agree.

**Comment by AlCalzone** [comment]
Will be possible in the next version.

**Comment by HubertusH** [comment]
Perfect! Thank you
