### ISSUE TITLE
Scrolling broken on devices.zwave-js.io

### ISSUE THREAD

**Issue by smiller171** [zwave-js/node-zwave-js#4695]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within ZWaveJS2MQTT?

NO, my problem is NOT within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

This very well may be the wrong place for this bug report. I'm happy to move it with guidance on the correct location.

What causes the bug?
Visiting [devices.zwave-js.io](https://devices.zwave-js.io/) on mobile. (specifically Chrome for Android)

What do you observe?
Scrolling is ignored both in the device list and in a specific device page.

What did you expect to happen?
To be able to scroll through devices and device information for reference on my phone.

  1. Go to [devices.zwave-js.io](https://devices.zwave-js.io/) on mobile.
  2. Attempt to scroll

### Device information

N/A

### How are you using `node-zwave-js`?

- [ ] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [ ] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version:
`node-zwave-js` branch:
`zwavejs2mqtt` branch:

### Did you change anything?

no

### Did this work before?

Yes (please describe)

### If yes, where did it work?

At some point in the past I was able to browse device docs on my phone. I can't provide an estimated timeline

### Attach Driver Logfile

N/A

**Comment by AlCalzone** [comment]
@marcus-j-davies

**Comment by marcus-j-davies** [comment]
Thanks @smiller171 
I don't have an android device to hand - but will spend some time looking into any behaviour traits, I need to factor in.

**Comment by marcus-j-davies** [comment]
@smiller171 
This is reported as working again - thanks for the report.

@AlCalzone 
This can be closed (I believe)

**Comment by smiller171** [comment]
Can confirm it's working as expected again, thanks.
