### ISSUE TITLE
Aeotec Smart Switch 6 showing up as dead

### ISSUE THREAD

**Issue by babeyrage** [zwave-js/node-zwave-js#4855]
Hi all, apologies if this is in the wrong section, but I am not sure where else to ask. I recently had to migrated my Ubuntu server to Proxmox and as a result reinstalled my docker setup. Previously my smart switch showed up in zwavejs2mqtt with no issues, and integrated into HA seamlessly, without a hitch. Since migrating to my new installation, my smart switch shows up dead, no matter what I do. I have reset to factory settings and I have tried re-interviewing and healing the network, but the device still just shows up as "dead". My USB Gen5 Z-Stick shows up in Zwave so I believe I have passed it through correctly. 

Any assistance would be greatly appreciated!

[zwavejs2mqtt-store.zip](https://github.com/zwave-js/zwavejs2mqtt/files/9189185/zwavejs2mqtt-store.zip)

**Comment by robertsLando** [comment]
I don't see any error in your logs, just wondering if there could be some connectivity issue or else, are you sure your device is working correctly? Did you factory resetted your device? In that case you should call replace failed node to re-include it

**Comment by AlCalzone** [comment]
> transmit status: NoAck

The controller can't reach the switch, which is no wonder if you factory reset it.

---

You can **replace failed node** to re-include it while keeping the node ID like @robertsLando said, or you can **remove failed node** on node 4 and include the switch again normally.

**Comment by babeyrage** [comment]
> I don't see any error in your logs, just wondering if there could be some connectivity issue or else, are you sure your device is working correctly? Did you factory resetted your device? In that case you should call replace failed node to re-include it

How would I check if the device is working correctly? It can be used a plug, the USB port on the side works, and when I follow the instructions to pair it to the USB stick, it seems to work correctly then. I've done the replace failed node, I've tried to re-interview the node and I've tried removing the failed node and then re-adding it. When I go through that process it just hangs on "Inclusion is started. Please put your device in inclusion mode", and make sure the plug has the purple LED around it but on the control panel, it just stays on that screen.

Below is a screenshot of the device on the control panel. Apologies for the weird screenshot, I'm responding from my mobile. 

![image](https://user-images.githubusercontent.com/106855541/181035598-2a3def37-647f-450a-9959-bf48ab75ea76.png)

**Comment by AlCalzone** [comment]
Please make a [driver log](https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/generating-logs?id=driver-logs) of these attempts, loglevel `debug` or `silly` and attach it here as a file.

**Comment by babeyrage** [comment]
I have done a driver log and attached it below, but I cannot attach the node export when going to Advanced -> Dump. 

[zwavejs2mqtt-store(1).zip](https://github.com/zwave-js/node-zwave-js/files/9199843/zwavejs2mqtt-store.1.zip)

**Comment by AlCalzone** [comment]
Are you waiting until the automatic NVM backup before inclusion is finished? That seems to take about 30 seconds for your stick. Any action you take while that happens won't result in a node being included.

Also @robertsLando does the default inclusion timeout of 30s take the backup into account?

**Comment by AlCalzone** [comment]
@babeyrage Looking closer, it looks like your stick is crashing and disconnecting when you try to include a node.
```
2022-07-27T13:50:30.803Z DRIVER » [REQ] [IsFailedNode]
                                    payload: 0x05
2022-07-27T13:50:30.805Z SERIAL « [ACK]                                                                   (0x06)
2022-07-27T13:50:30.805Z SERIAL « 0x010401620199                                                       (6 bytes)
2022-07-27T13:50:30.806Z SERIAL » [ACK]                                                                   (0x06)
2022-07-27T13:50:30.807Z DRIVER « [RES] [IsFailedNode]
                                    payload: 0x01
2022-07-27T13:53:46.544Z DRIVER   Serial port errored: The serial port closed unexpectedly! (ZW0100)
2022-07-27T13:53:46.546Z DRIVER   destroying driver instance...
2022-07-27T13:53:46.580Z DRIVER   driver instance destroyed
```

```
2022-07-27T13:56:57.118Z CNTRLR   handling replace node request (status = FailedNodeReplace)
2022-07-27T13:56:57.118Z CNTRLR   The failed node is ready to be replaced, inclusion started...
2022-07-27T13:56:57.119Z DRIVER       the message was handled
2022-07-27T13:57:10.146Z DRIVER   Serial port errored: The serial port closed unexpectedly! (ZW0100)
2022-07-27T13:57:10.149Z DRIVER   destroying driver instance...
2022-07-27T13:57:10.185Z DRIVER   driver instance destroyed
```

**Comment by babeyrage** [comment]
Hmm, that is strange. Do I need to run the docker container in privileged mode due to the fact it's running on a Proxmox host? Or could it be that I have not passed it through correctly? I doubt it could be that because it wouldn't show up if I hadn't passed it correctly.

**Comment by AlCalzone** [comment]
Honestly I don't know. This is something I haven't seen before.

If you have another stick you could check if the same happens there.

**Comment by babeyrage** [comment]
Ok, so I think I solved the issue of the of the stick crashing. I had it passed it through as USB 3, so I removed it and then passed it through again without the "USB 3" option ticked in Proxmox, but I still am not able to re-interview or replace the failed nodes :(

[zwavejs_2022-07-28.log](https://github.com/zwave-js/node-zwave-js/files/9209924/zwavejs_2022-07-28.log)

**Comment by babeyrage** [comment]
Boy howdy I am at a loss here. I have done a factory reset on the USB gateway and both smart switches, gone through and included them again onto the USB gateway, but I am still not getting anything from both of them. Logs are still coming back saying "node is dead, status: no ACK". @AlCalzone, @robertsLando is there a "privileged" docker command for zwavejs2mqtt, seen as though I'm running it on a Proxmox host? As I previously said, when I was just running Ubuntu server as the host OS, I had no issues getting the nodes added to zwavejs2mqtt through Docker. Can you guys think of anything else I could try?

**Comment by robertsLando** [comment]
@babeyrage try to disable soft reset in settings, cannot see logs right now (I'm on my phone) but are you using serial-by/id path for your stick?

**Comment by babeyrage** [comment]
I have disabled the soft reset and that doesn't change anything. I've upgraded the firmware on both the Z-Stick and the smart switch, but still not getting anything. Just going to ask a stupid question here, to further rule anything out, if I'm running zwavejs2mqtt I don't need to run the zwavejs server correct? 

And I am using the serial-by-id in the docker compose. 

To further test, I spun up another Ubuntu VM on proxmox, passed through the USB stick (in a different port this time), and installed zwavejs2mqtt through snap, and I am having the same issue. I have also upgraded the firmware on both the z-stick and the switches which unfortunately did not solve anything either

**Comment by robertsLando** [comment]
> Just going to ask a stupid question here, to further rule anything out, if I'm running zwavejs2mqtt I don't need to run the zwavejs server correct?

Nope, you don't as it is already shipped within zwavejs2mqtt

> To further test, I spun up another Ubuntu VM on proxmox, passed through the USB stick (in a different port this time), and installed zwavejs2mqtt through snap, and I am having the same issue. I have also upgraded the firmware on both the z-stick and the switches which unfortunately did not solve anything either

I really dunno what's going on here, could simply be that your stick is broken? @AlCalzone any other ideas?

**Comment by AlCalzone** [comment]
> "node is dead, status: no ACK"

is NOT a communication issue between Z-Wave JS and the stick. This is an issue of physical between the stick and the nodes.
So it does look like you solved the first part of the issue, now to figure out why it doesn't see the devices:

1. Put the stick on a USB extension cable, not directly in a USB port, not in the back of a server, and away from metallic surfaces
2. If that doesn't help, bring the node and device together as close as you can (in the order of a meter or so)
3. If that doesn't help, provide logs - maybe we'll see something else then.

**Comment by babeyrage** [comment]
> > "node is dead, status: no ACK"
> 
> is NOT a communication issue between Z-Wave JS and the stick. This is an issue of physical between the stick and the nodes. So it does look like you solved the first part of the issue, now to figure out why it doesn't see the devices:
> 
>     1. Put the stick on a USB extension cable, not directly in a USB port, not in the back of a server, and away from metallic surfaces
> 
>     2. If that doesn't help, bring the node and device together as close as you can (in the order of a meter or so)
> 
>     3. If that doesn't help, provide logs - maybe we'll see something else then.

OMG, we have a winner! I put the USB stick on an extension cable as you said, and although I still had to tinker a bit on the control panel, I have got both smart switches up and communicating and working as they should. Thanks to the both of you @AlCalzone & @robertsLando for the assistance. Really appreciate it :)

**Comment by AlCalzone** [comment]
If you haven't already, do a network heal now to make sure the devices get updated routes.
