### ISSUE TITLE
Invalid battery values are created for a Battery CC V1 supporting device

### ISSUE THREAD

**Issue by kpine** [zwave-js/node-zwave-js#5252]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within Z-Wave JS UI (formerly ZwaveJS2MQTT)?

NO, my problem is NOT within Z-Wave JS UI

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug?
Presumably, Z-Wave JS assumes the highest CC version is supported when it doesn't know what the version is.

What do you observe?
I started a re-interview. The interview process was hung in Protocol Info. The device sent an unsolicited battery report consisting of only battery level and is low. The driver created metadata for all of the V3 values, but assigned no values. Those show up as "undefined" in Z-Wave JS UI.

Should applications handle metadata events prior to value added events?

![image](https://user-images.githubusercontent.com/791794/207528509-eff41b24-eecb-4762-8a02-ba0697d7c65c.png)

What did you expect to happen?

Values that aren't supported aren't created.

After the interview completed successfully, and it was determined that only Battery CC V1 was supported, the undefined values still existed. At that point I'd expect they were at least removed.

  1. Cause an interview of a battery device to hang at Protocol Info (Zooz ZSE41 and ZSE42) are good at this
  2. Wait for the device to send a battery report.
  3. Observe the invalid values.

### Device information

Manufacturer: Zooz
Model name: ZSE41
Node ID in your network: 4

### How are you using `node-zwave-js`?

- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (latest)
- [X] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (dev)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [ ] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version:
`node-zwave-js` branch: 8.6.0.01c659b
`zwave-js-ui` branch: 10.3.1

### Did you change anything?

no

### Did this work before?

Don't know, this is a new device

### If yes, where did it work?

I ran into this while debugging another issue, so I can't say I've seen it outside of that. I know many HA users have seen bogus battery reports before, that could be for other reasons, like a failed interview (?).

### Attach Driver Logfile

[zwavejs_current.log](https://github.com/zwave-js/node-zwave-js/files/10225208/zwavejs_current.log)

**Comment by AlCalzone** [comment]
I think the issue is that the battery report comes in during the interview, but before the Battery CC version has been queried.
As a result, the implemented version in Z-Wave JS is used to determine which values get created.
