### ISSUE TITLE
Set controller region and tx power settings on startup, based on configuration

### ISSUE THREAD

**Issue by kpine** [zwave-js/node-zwave-js#6149]
**Is your feature request related to a problem? Please describe.**

There have been several occasions where a user upgrades their 700-series controller, and the region and power level settings are reset. For example, the region was US, but the f/w upgrade changes it to EU. Now suddenly everything in the network will be dead, and uninformed users are left wondering how to troubleshoot. Worse, if you're using Home Assistant to upgrade, it does not even allow you to change the region, so your only choice is to change the software.

**Describe the solution you'd like**

Allow region and tx settings to be specified in the driver settings. The driver can apply these settings on startup to ensure they are always correct. If the settings are not configured, use the current behavior and don't set it on startup.

Something like:

```
Get RF Region
If RF Region result != region configuration and region configuration is set:
    Set RF Region to configuration value if supported
    If Set RF Region is not supported:
        log an error to indicate region not supported and doesn't match configuration
```

**Describe alternatives you've considered**
Keep the current behavior.

**Additional context**
This is how all both of the SiLabs controller gateways have been designed (zipgateway and now zpc).

**Comment by AlCalzone** [comment]
I seriously wonder how this was never proposed in the last 5 years ‍🤷‍♂️
